#Docker compose for SEAM News
version: '3.7'

services:
  server:
    build:
      context: ./tweet_monitoring_service
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./tweet_monitoring_service/.env
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
        db:
          condition: service_healthy

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./tweet_monitoring_service/.env
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgres_data:
